name: Lint

# Grabbed from https://black.readthedocs.io/en/stable/github_actions.html

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
